// Mocks generated by Mockito 5.4.6 from annotations
// in posts_app/test/presentation/providers/comments_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:posts_app/data/models/comment_model.dart' as _i5;
import 'package:posts_app/data/models/post_model.dart' as _i2;
import 'package:posts_app/data/repositories/post_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePost_0 extends _i1.SmartFake implements _i2.Post {
  _FakePost_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Post>> getPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, []),
            returnValue: _i4.Future<List<_i2.Post>>.value(<_i2.Post>[]),
          )
          as _i4.Future<List<_i2.Post>>);

  @override
  _i4.Future<_i2.Post> getPost(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [id]),
            returnValue: _i4.Future<_i2.Post>.value(
              _FakePost_0(this, Invocation.method(#getPost, [id])),
            ),
          )
          as _i4.Future<_i2.Post>);

  @override
  _i4.Future<List<_i5.Comment>> getComments(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [postId]),
            returnValue: _i4.Future<List<_i5.Comment>>.value(<_i5.Comment>[]),
          )
          as _i4.Future<List<_i5.Comment>>);

  @override
  _i4.Future<_i2.Post> createPost({
    required String? title,
    required String? body,
    int? userId = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #title: title,
              #body: body,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Post>.value(
              _FakePost_0(
                this,
                Invocation.method(#createPost, [], {
                  #title: title,
                  #body: body,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Post>);

  @override
  _i4.Future<_i2.Post> updatePost(_i2.Post? post) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [post]),
            returnValue: _i4.Future<_i2.Post>.value(
              _FakePost_0(this, Invocation.method(#updatePost, [post])),
            ),
          )
          as _i4.Future<_i2.Post>);

  @override
  _i4.Future<void> deletePost(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
